// src/Modals/AddGrp.tsx
import React, { useEffect, useState } from "react";
import { appWindow } from "@tauri-apps/api/window";
import { emit } from "@tauri-apps/api/event";

export default function AddGrp() {
  const [errorLabel, setErrorLabel] = useState<string>("");

  const [grpTitle, setGrpTitle] = useState<string>("");

  const [grpData, setGrpData] = useState<{
    slotId: number;
    nodeId: number;
    type: string;
  }>({
    slotId: -1,
    nodeId: -1,
    type: "node",
  });

  console.log("hai");

  function cancel() {
    appWindow.hide();
  }

  function apply() {
    setErrorLabel("");

    emit(
      "backData",
      JSON.stringify({
        action: "addGrp",
        payload: {
          grpTitle,
          ...grpData,
        },
      })
    ).then(() => appWindow.hide());
  }

  appWindow.listen("data", (e) => {
    setGrpData(JSON.parse(e.payload as string));
  });

  return (
    <div className="container">
      <div className="my-3">
        <label htmlFor="grpName" className="form-label">
          Group title:
        </label>
        <input
          type="text"
          className="form-control"
          value={grpTitle}
          onChange={(e) => {
            setGrpTitle(e.target.value);
          }}
        />
        <small className="text-danger">{errorLabel}</small>
      </div>
      <hr />
      <p className="my-2" style={{ height: 40 }}>
        You will be adding a new group before
        <b>{` ${grpData.type} ${grpData.nodeId} `}</b>
        and will affect it to all the {grpData.type + `s`} after it.
      </p>
      <div className="float-end">
        <button type="button" className="btn btn-danger" onClick={cancel}>
          Cancel
        </button>
        <button
          type="button"
          className="btn btn-primary"
          onClick={apply}
          disabled={grpTitle.length == 0}
        >
          Apply
        </button>
      </div>
    </div>
  );
}

// src/views/Modals/Groups/AddGrp.vue
<template>
    <div class="container">
        <div class="mb-3">
            <label for="grpName" class="form-label">Group title:</label>
            <input type="text" class="form-control" v-model="grpData.title" />
        </div>
        <hr />
        <p style="min-height: 40px; max-height: 40px;">
            You will be adding a new group named
            <b style="color:white;">{{ grpData.title }}</b> before
            <b style="color:white;">{{ grpData.type + ` ` + grpData.id }}</b>
            and will affect it to all the {{ grpData.type + `s` }} after it.
        </p>
        <div class="float-end">
            <button type="button" class="btn btn-secondary" @click="cancel()">
                Cancel
            </button>
            <button type="button" class="btn btn-primary" @click="apply()">
                Apply
            </button>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { Watch } from "@/components/vue-decorator";
import { ipcRenderer } from "electron";

const remote = require("electron").remote;

interface DataType {
    type: string;
    id: number;
    title: string;
}

export default class AddGrp extends Vue {
    private grpData: DataType = {
        type: "node", //"beam"
        id: -1,
        title: ""
    };

    mounted() {
        ipcRenderer.on("data", (event, arg) => {
            this.grpData = arg;
        });
    }

    cancel() {
        remote.getCurrentWindow().hide();
    }

    apply() {
        ipcRenderer.send("grpEdit", {
            func: "add",
            data: JSON.parse(JSON.stringify(this.grpData))
        });
        remote.getCurrentWindow().hide();
    }
}
</script>

<style></style>
